apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-deployment
  labels:
    app: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - name: probes-db-api
        image: cltau/fakedb-api:v1
        ports:
        - containerPort: 8001
        startupProbe:
          httpGet:
            path: /startup
            port: 8001
          failureThreshold: 30
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8001
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8001
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3